### PR TITLE
STADTPULS-561: feat(rpc): Adds view for extended_user_profiles

### PR DESCRIPTION
**Pull request by ff6347**
Currently result of query looks like this

| id                                   | username | display_name | created_at                    | link | description | sensors_count | records_count | categories |
|--------------------------------------|----------|--------------|-------------------------------|------|-------------|---------------|---------------|------------|
| c6c4c18c-e6d2-4005-929c-ccf31c6d4702 | one      |              | 2021-11-30 18:00:32.742219+00 |      |             |             0 |               | {}         |
| fe09363f-5af9-4ec4-8d96-a0aeb46469a9 | three    |              | 2021-11-30 18:00:47.341474+00 |      |             |             5 |         15432 | {1,2}      |
| d3435954-cdd2-473f-b408-87c119264bdb | two      |              | 2021-11-30 18:00:42.736645+00 |      |             |             5 |         10000 | {1,5}      |

Requested was a function that can fulfill this interface.

```ts
export interface ParsedAccountType {
id: string;
username: string;
displayName: string;
createdAt: string;
link?: string;
description?: string;
categories: definitions["categories"]["id"][];
sensorsCount: number;
recordsCount: number;
sensors: ParsedSensorType[];
}```
See [the source](https://github.com/technologiestiftung/stadtpuls-frontend/blob/61dc3d41e15a6000fbd490fd81b3cc2abdbcc8fd/src/lib/hooks/usePublicAccounts/index.ts#L32-L43)

I'm not sure if we should aggregate all sensors into this one query. It could be inserted as JSON but maybe this is to much? @dnsos

### CODE REVIEW

**Review by dnsos — COMMENTED** [review]
> I'm not sure if we should aggregate all sensors into this one query. It could be inserted as JSON but maybe this is to much?

Agree. I would be fine with fetching it separately. It's overkill anyway. Even for the sensor cards we only need a very limited amount of information and records.

**Comment by ff6347** [comment]
@dnsos so we keep this function like this? Is it approved?

**Comment by dnsos** [comment]
Hey @ff6347, sorry I had actually approved this earlier today right after requesting another review. But it seems to have gotten lost in the void 😮

**Review by dnsos — DISMISSED** [review]

**Comment by ff6347** [comment]
No problemo. If you need this in staging I can merge this later on and apply it

**Comment by dnsos** [comment]
> If you need this in staging I can merge this later on and apply it

Yes please, thank you!

**Pull request merged**
